# Generated by Django 4.2.5 on 2023-12-26 08:16

from django.db import migrations, models
import django.db.models.deletion
import main.views.Create.<locals>


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'model1',
                'db_table': 'main_model1',
            },
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'model2',
                'db_table': 'main_model2',
            },
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'model3',
                'db_table': 'main_model3',
            },
        ),
        migrations.CreateModel(
            name='Modelt4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'modelt4',
                'db_table': 'main_modelt4',
            },
        ),
        migrations.CreateModel(
            name='Modelt5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'modelt5',
                'db_table': 'main_modelt5',
            },
        ),
        migrations.CreateModel(
            name='Modelt6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('fkey', main.views.Create.<locals>.NewForeignKeyField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='model1')),
            ],
            options={
                'verbose_name': 'modelt6',
                'db_table': 'main_modelt6',
            },
        ),
    ]
