# Generated by Django 4.2.5 on 2023-11-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_delete_ktest3_delete_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
