# Generated by Django 4.2.5 on 2023-11-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_model1_model2_model3_model5_model6_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.DeleteModel(
            name='Model2',
        ),
        migrations.DeleteModel(
            name='Model3',
        ),
        migrations.DeleteModel(
            name='Model5',
        ),
        migrations.DeleteModel(
            name='Model6',
        ),
    ]
