# Generated by Django 4.2.5 on 2023-11-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_model1_delete_model2_delete_model3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
